#!/bin/bash
rsync -r website root@wcpm.emeraldcode.com:~/
ssh root@wcpm.emeraldcode.com bash -c "'
cd website
forever stopall
export PORT=80
#export SSL_PORT=443
export API='\''https://api.wcpm.com/api'\''
npm rebuild
forever start app.js
'"
